### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by bienjaroslav** [emreesen27/Flutter-Sign-in-Button#10]
hello,

any plans to support dark mode variants for Google, Facebook... ?

thanks.

**Comment by emreesen27** [comment]
Hello,
Are you talking about buttons that change according to the device theme?

**Comment by bienjaroslav** [comment]
hello,

I believe it would be enough to be able to select the mode manually, just to support it off-the-shelf like ButtonType.googleDark, and similar. My point is if you could consider having that choice part of the library.

Google and others might have their requirements for showing the 'sign in' button in dark mode. For Google see the design [Sign-In Branding Guidelines](https://developers.facebook.com/docs/facebook-login/userexperience/#buttondesign).

Thanks in advance for your feedback.

**Comment by emreesen27** [comment]
I can make such an improvement soon. Thanks for your advice.

**Comment by emreesen27** [comment]
* Upgrade to version 1.0.2

<b>Facebook Dark</b>
```dart 
buttonType: ButtonType.facebookDark,
```
<b>Google Dark</b>
```dart 
buttonType: ButtonType.googleDark,
```
If this solves your problem, you can close this issue.
