### ISSUE TITLE
Dark Apple Button

### ISSUE THREAD

**Issue by shinriyo** [emreesen27/Flutter-Sign-in-Button#11]
Could you add Dark Apple Button?

**Comment by emreesen27** [comment]
I don't know if this is necessary for apple. The library allows to change the background and text color.

**Comment by adeolaex** [comment]
It is it's in their guidelines. The current colour scheme is not accepted as per [this](https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/).

**Comment by shinriyo** [comment]
@adeolaex

**Comment by shinriyo** [comment]
Thank you

**Comment by emreesen27** [comment]
* Upgrade to version 2.0.1

```dart
SignInButton(
    buttonType: ButtonType.apple,
    onPressed: () {}),
```
```dart
SignInButton(
   buttonType: ButtonType.appleDark,
   shape: RoundedRectangleBorder(
     borderRadius: BorderRadius.circular(5.0),
   ),
onPressed: () {}),
```

![ss](https://user-images.githubusercontent.com/45034416/129789241-8adb6619-63f2-48da-8d67-c4fd6ab9da74.png)

**Comment by shinriyo** [comment]
thank you for updating!
