### ISSUE TITLE
Add dark icon for for github

### ISSUE THREAD

**Issue by jagadish-pattanaik** [emreesen27/Flutter-Sign-in-Button#13]
white colour github image i.e darkgithub icon

**Comment by omonimus1** [comment]
I think you can customize the background and text color @jagadish-pattanaik

**Comment by jagadish-pattanaik** [comment]
Yes background and text can be customized but the icon cant be changed from dark colour to white, I want a white icon so that I can place it in between a dark coloured background.

**Comment by emreesen27** [comment]
- Upgrade version to 2.0.2
```yaml
sign_button: ^2.0.2
```


- Now you can use

```dart
 buttonType: ButtonType.githubDark,
```
