### ISSUE TITLE
Possibility to disabled the button

### ISSUE THREAD

**Issue by NatsuOnFire** [emreesen27/Flutter-Sign-in-Button#15]
In SignInButton it's impossible to put null on onPressed because it's a required parameter.
Can you make it nullable?

**Comment by emreesen27** [comment]
Hi,
The login buttons are derived from the Material Button. Onpress is a required field.

Why do you want to leave this field null?

**Comment by NatsuOnFire** [comment]
I found this in MaterialButton code : 
```
  /// The callback that is called when the button is tapped or otherwise activated.
  ///
  /// If this callback and [onLongPress] are null, then the button will be disabled.
  ///
  /// See also:
  ///
  ///  * [enabled], which is true if the button is enabled.
  final VoidCallback? onPressed;

  /// The callback that is called when the button is long-pressed.
  ///
  /// If this callback and [onPressed] are null, then the button will be disabled.
  ///
  /// See also:
  ///
  ///  * [enabled], which is true if the button is enabled.
  final VoidCallback? onLongPress;
```

The field onPress is required but can be null according to the documentation. This allow to have a disabled effect.
This code work fine : 
`MaterialButton(onPressed: null);`

**Comment by NatsuOnFire** [comment]
I think you just have to change your onPress in SignInButton class to : 
```
   //required
  /// [onPressed] Send a function to trigger the button.
  Function? onPressed;
```

**Comment by emreesen27** [comment]
yes I know, but this improvement causes some buttons to disappear and only their icons to appear. Not a good use. If you have a solution for this, you can open pr.

**Comment by NatsuOnFire** [comment]
Alright, I'll take a look and test on my own to find a solution. 👌

**Comment by emreesen27** [comment]
Thanks for your contribution.

You can now upgrade to version 2.0.1

**Comment by NatsuOnFire** [comment]
You're welcome, it was a pleasure 😄
