### ISSUE TITLE
googleDark should have a black background?

### ISSUE THREAD

**Issue by giorgio79** [emreesen27/Flutter-Sign-in-Button#17]
Hello,

Noticed googleDark has a Facebook like blue backgroud instead of black.

Can you correct it?

Alternatively, could we have a custom background color setting perhaps? So you dont have to hardcode these variables?

**Comment by emreesen27** [comment]
Hello, 
The back color of the button is designed to match the document. [Sign-In Branding Guidelines](https://developers.google.com/identity/branding-guidelines)

But you can set the background color as you wish.

```dart 
 btnColor: Colors.white,
```

**Comment by giorgio79** [comment]
Wow thx. I notice Google is strick about the background color. I guess we will leave it at that then :) Much appreciated
