### ISSUE TITLE
Add phone number button

### ISSUE THREAD

**Issue by Finni123** [emreesen27/Flutter-Sign-in-Button#27]
I love this plugin but I'm missing the phone login option.
It should be pretty easy to add, right?

**Comment by LOGESH-B** [comment]
Hii @Finni123 
I am interested to work on this.....can you tell me how to setup the dev enviromnment after forking the repo

**Comment by emreesen27** [comment]
Hi @Finni123 

Instead of adding a button type, I made the image changeable. In this way, you can make any customization you want.


* Upgrade to version 2.0.6


```dart
SignInButton(
  buttonType: ButtonType.custom,
  width: 230,
  customImage: CustomImage("images/phone.png"),
  btnText: "Sign in with phone number",
  onPressed: () {
    setState(() {
      _buttonClick = "phone number";
    });
  }),
```
